### ISSUE TITLE
[1.16] ToP's GUI Renderer breaks Forge GUI Stacking

### ISSUE THREAD

**Issue by Shadows-of-Fire** [McJty/TheOneProbe#551]
This is caused by the following render code not calling `ForgeHooksClient#getGuiFarPlane` and instead using a constant `3000.0F`
<https://github.com/McJtyMods/TheOneProbe/blob/1.16/src/main/java/mcjty/theoneprobe/rendering/OverlayRenderer.java#L128>

This is not present in 1.18, as it has been fixed as visible here <https://github.com/McJtyMods/TheOneProbe/blob/1.18/src/main/java/mcjty/theoneprobe/rendering/OverlayRenderer.java#L132>

GUI Stacking was added in `36.2.9`, so that call is likely not present until you update to/past that forge version.

**Comment by McJty** [comment]
Fix is ready in git. Will release later today

**Comment by McJty** [comment]
Latest version on maven has the fix

**Comment by McJty** [comment]
Fix released

**Comment by Shadows-of-Fire** [comment]
It looks like that did not fix it, I think this call also needs to be updated https://github.com/McJtyMods/TheOneProbe/blob/1.16/src/main/java/mcjty/theoneprobe/rendering/OverlayRenderer.java#L132
The patched vanilla code is `RenderSystem.translatef(0.0F, 0.0F, 1000.0F - net.minecraftforge.client.ForgeHooksClient.getGuiFarPlane());`

**Comment by Shadows-of-Fire** [comment]
That change is also reflected in the 1.18 branch here <https://github.com/McJtyMods/TheOneProbe/blob/1.18/src/main/java/mcjty/theoneprobe/rendering/OverlayRenderer.java#L135>

**Comment by Shadows-of-Fire** [comment]
Applied that change locally and built a test jar, that is indeed the remaining part that's breaking it.

**Comment by McJty** [comment]
Oops sorry. Well should be fixed now then
